// Generated by Running Blitz Character Creation Wizard
// Character: Donut

function createDonutCharacter() {
    const donutGroup = new THREE.Group();
    
    // Create body
    const body = createDonutBody();
    donutGroup.add(body);
    
    // Add features
        const eyes = createDonutEyes();
    donutGroup.add(eyes);

    const accessory = createDonutAccessory();
    donutGroup.add(accessory);


    
    // Apply transformations
    donutGroup.scale.set(1, 1, 1);
    
    return donutGroup;
}

function createDonutBody() {
    const geometry = new THREE.TorusGeometry(0.4, 0.2, 8, 16);
    
    const material = new THREE.MeshStandardMaterial({
        color: 0xFF6B6B,
        metalness: 0.5,
        roughness: 0.7
    });
    
    const mesh = new THREE.Mesh(geometry, material);
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    
    return mesh;
}


function createDonutEyes() {
    const eyeGroup = new THREE.Group();

    const eyeGeometry = new THREE.SphereGeometry(0.08, 8, 8);
    const eyeMaterial = new THREE.MeshStandardMaterial({
        color: 0x00ffff,
        emissive: 0x004444,
        emissiveIntensity: 0.5
    });

    const leftEye = new THREE.Mesh(eyeGeometry, eyeMaterial);
    leftEye.position.set(-0.15, 0.1, 0.4);

    const rightEye = new THREE.Mesh(eyeGeometry, eyeMaterial);
    rightEye.position.set(0.15, 0.1, 0.4);

    eyeGroup.add(leftEye, rightEye);

    return eyeGroup;
}

function createDonutAccessory() {
    const accessoryGroup = new THREE.Group();

    const brimGeometry = new THREE.CylinderGeometry(0.6, 0.6, 0.05, 16);
    const brimMaterial = new THREE.MeshStandardMaterial({ color: 0x8B4513 });
    const brim = new THREE.Mesh(brimGeometry, brimMaterial);
    brim.position.set(0, 0.45, 0);

    const crownGeometry = new THREE.CylinderGeometry(0.35, 0.35, 0.3, 16);
    const crownMaterial = new THREE.MeshStandardMaterial({ color: 0x654321 });
    const crown = new THREE.Mesh(crownGeometry, crownMaterial);
    crown.position.set(0, 0.6, 0);

    accessoryGroup.add(brim, crown);

    return accessoryGroup;
}


// Character metadata
const donutCharacterData = {
    id: 'donut',
    name: 'Donut',
    description: 'Chocolate Glaze!',
    abilities: [],
    tags: ['food', 'custom', 'wizard-created'],
    createFunction: 'createDonutCharacter'
};

// Export to global scope
if (typeof window !== 'undefined') {
    window.createDonutCharacter = createDonutCharacter;
    window.donutCharacterData = donutCharacterData;
}